### PR TITLE
OOPObjectsAndClasses_AleksandraMihaylova

### PR DESCRIPTION
**Pull request by aleksandramihaylova**

### CODE REVIEW

**Comment by iivanov00** [comment]
The package is not named correctly.

**Comment by aleksandramihaylova** [comment]
> The package is not named correctly.

I edited then name.

**Comment by iivanov00** [comment]
> > The package is not named correctly.
> 
> I edited then name.

Still not named correctly it should be exerciseName_YourName

**Comment by aleksandramihaylova** [comment]
> > > The package is not named correctly.
> > 
> > 
> > I edited then name.
> 
> Still not named correctly it should be exerciseName_YourName

I apologise. It is changed now. I hope it is correct.

**Pull request closed without merging**
